apiVersion: v1
kind: Pod
metadata:
  name: sa-test-pod
  namespace: sa-exercise
spec:
  serviceAccountName: my-service-account
  containers:
  - name: curl-container
    image: curlimages/curl
    command: ["sh", "-c", "sleep 3600"]